<?php
    require_once dirname(dirname(__DIR__)) . '/bootstrap.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JSON Configuration Schemas - Frontline Framework</title>

    <link rel="icon" href="/php/admin/assets/img/favicon.ico">
    <link rel="stylesheet" href="//fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
    <link rel="stylesheet" href="/php/admin/docs/style.css">
</head>
<body>
    <div class="docs-container">
        <!-- Header -->
        <header class="docs-header">
            <div class="header-content">
                <div class="logo-section">
                    <img src="/php/admin/assets/img/logo.png" alt="Frontline Framework" class="logo">
                    <div>
                        <h1>JSON Configuration Schemas</h1>
                        <p>Data structure reference for configuration files</p>
                    </div>
                </div>
                <a href="index.php" class="btn-back">
                    <i class="fas fa-arrow-left"></i>
                    Documentation Home
                </a>
            </div>
        </header>

        <!-- Main Content -->
        <main class="docs-main">
            <div class="docs-content">
                <!-- Breadcrumb -->
                <nav class="breadcrumb">
                    <a href="index.php"><i class="fas fa-home"></i> Home</a>
                    <span>/</span>
                    <a href="index.php#technical">Technical Reference</a>
                    <span>/</span>
                    <span>JSON Configuration</span>
                </nav>

                <h1 class="page-title">JSON Configuration Schemas</h1>
                <p class="page-subtitle">Complete reference for all JSON configuration file structures used by the Frontline Framework.</p>

                <!-- Overview -->
                <section class="content-section">
                    <h2><i class="fas fa-file-code"></i> Overview</h2>
                    <p>The Frontline Framework stores all site configuration, content, and settings in JSON files. These files are generated by the interface, committed to Git, and consumed by deployment scripts on the Kinsta server. Understanding the JSON structure is essential for troubleshooting, advanced customizations, and manual configurations.</p>

                    <div class="alert alert-info">
                        <div class="alert-title">
                            <i class="fas fa-info-circle"></i>
                            Why JSON?
                        </div>
                        <ul>
                            <li><strong>Version Control:</strong> Text-based format works perfectly with Git</li>
                            <li><strong>Machine-Readable:</strong> Easy to parse in PHP, JavaScript, Bash, and Python</li>
                            <li><strong>Human-Readable:</strong> Developers can read and edit configurations</li>
                            <li><strong>Validation:</strong> JSON syntax can be validated before deployment</li>
                        </ul>
                    </div>
                </section>

                <!-- site.json -->
                <section class="content-section">
                    <h2><i class="fas fa-globe"></i> site.json - Core Site Configuration</h2>
                    <p>Contains fundamental site information like title, URL, and WordPress admin credentials.</p>

                    <h3>Schema</h3>
                    <pre><code>{
    "site_name": "string",           // Site title (appears in browser tab, admin)
    "site_url": "string",             // Full site URL including https://
    "site_tagline": "string",         // Site description/tagline
    "admin_email": "string",          // WordPress admin email
    "admin_username": "string",       // WordPress admin login username
    "admin_password": "string",       // WordPress admin password (encrypted in storage)
    "timezone": "string",             // PHP timezone (e.g., "America/New_York")
    "language": "string",             // WordPress language code (default: "en_US")
    "date_format": "string",          // Date display format (e.g., "F j, Y")
    "time_format": "string",          // Time display format (e.g., "g:i a")
    "start_of_week": "integer"        // 0 = Sunday, 1 = Monday
}</code></pre>

                    <h3>Example</h3>
                    <pre><code>{
    "site_name": "Senator Jane Doe for Congress",
    "site_url": "https://janedoe2026.com",
    "site_tagline": "Fighting for Working Families",
    "admin_email": "admin@janedoe2026.com",
    "admin_username": "jadmin",
    "admin_password": "$2y$10$encrypted_hash_here",
    "timezone": "America/Los_Angeles",
    "language": "en_US",
    "date_format": "F j, Y",
    "time_format": "g:i a",
    "start_of_week": 0
}</code></pre>

                    <div class="alert alert-warning">
                        <strong>Security Note:</strong> Passwords are encrypted before storage. Never commit plaintext passwords to repositories.
                    </div>
                </section>

                <!-- theme-config.json -->
                <section class="content-section">
                    <h2><i class="fas fa-palette"></i> theme-config.json - Theme Settings</h2>
                    <p>Controls theme selection, branding (logos, colors), and theme-specific options.</p>

                    <h3>Schema</h3>
                    <pre><code>{
    "theme_name": "string",           // Theme slug (BurBank, Candidate, Political, etc.)
    "theme_version": "string",        // Theme version number
    "branding": {
        "logo_url": "string",         // Path to primary logo image
        "logo_alt_text": "string",    // Logo alt text for accessibility
        "favicon_url": "string",      // Path to favicon (16x16 or 32x32 PNG/ICO)
        "primary_color": "string",    // Hex color code (e.g., "#14b8a6")
        "secondary_color": "string",  // Hex color code
        "accent_color": "string",     // Hex color code
        "text_color": "string",       // Hex color code for body text
        "heading_color": "string",    // Hex color code for headings
        "link_color": "string"        // Hex color code for links
    },
    "typography": {
        "heading_font": "string",     // Google Font name (e.g., "Montserrat")
        "body_font": "string",        // Google Font name (e.g., "Open Sans")
        "font_size_base": "string"    // Base font size (e.g., "16px")
    },
    "layout": {
        "site_width": "string",       // Max content width (e.g., "1200px")
        "sidebar_position": "string", // "left", "right", or "none"
        "header_style": "string",     // "transparent", "solid", or "sticky"
        "footer_widgets": "integer"   // Number of footer widget areas (1-4)
    },
    "features": {
        "blog_enabled": "boolean",
        "donations_enabled": "boolean",
        "events_enabled": "boolean",
        "volunteer_enabled": "boolean",
        "newsletter_enabled": "boolean"
    }
}</code></pre>

                    <h3>Example</h3>
                    <pre><code>{
    "theme_name": "BurBank",
    "theme_version": "2.1.0",
    "branding": {
        "logo_url": "/wp-content/uploads/2026/01/logo.png",
        "logo_alt_text": "Jane Doe for Congress",
        "favicon_url": "/wp-content/uploads/2026/01/favicon.ico",
        "primary_color": "#14b8a6",
        "secondary_color": "#1e40af",
        "accent_color": "#f59e0b",
        "text_color": "#1f2937",
        "heading_color": "#111827",
        "link_color": "#14b8a6"
    },
    "typography": {
        "heading_font": "Montserrat",
        "body_font": "Open Sans",
        "font_size_base": "16px"
    },
    "layout": {
        "site_width": "1200px",
        "sidebar_position": "right",
        "header_style": "sticky",
        "footer_widgets": 3
    },
    "features": {
        "blog_enabled": true,
        "donations_enabled": true,
        "events_enabled": false,
        "volunteer_enabled": true,
        "newsletter_enabled": true
    }
}</code></pre>
                </section>

                <!-- config.json -->
                <section class="content-section">
                    <h2><i class="fas fa-cog"></i> config.json - Main Configuration</h2>
                    <p>Central configuration file that merges settings from site.json, theme-config.json, and adds deployment-specific options.</p>

                    <h3>Schema</h3>
                    <pre><code>{
    "site": {
        // Contents of site.json merged here
    },
    "theme": {
        // Contents of theme-config.json merged here
    },
    "deployment": {
        "kinsta_site_id": "string",   // Kinsta site identifier
        "kinsta_environment": "string", // "live" or "staging"
        "git_repository": "string",    // GitHub repo (owner/repo)
        "git_branch": "string",        // Deployment branch (usually "main")
        "deploy_timestamp": "string",  // ISO 8601 timestamp
        "deploy_user": "string"        // User who triggered deployment
    },
    "plugins": {
        "required": ["array"],         // Plugins that must be installed
        "recommended": ["array"]       // Optional plugins
    },
    "security": {
        "geo_blocking": {
            "enabled": "boolean",
            "allowed_countries": ["array"], // ISO country codes
            "blocked_countries": ["array"],
            "mode": "string"           // "whitelist" or "blacklist"
        },
        "login_protection": {
            "two_factor": "boolean",
            "captcha": "boolean",
            "limit_attempts": "integer"
        }
    },
    "analytics": {
        "google_analytics_id": "string",
        "google_tag_manager_id": "string",
        "facebook_pixel_id": "string"
    }
}</code></pre>

                    <h3>Example</h3>
                    <pre><code>{
    "site": {
        "site_name": "Senator Jane Doe for Congress",
        "site_url": "https://janedoe2026.com"
    },
    "theme": {
        "theme_name": "BurBank",
        "branding": {
            "primary_color": "#14b8a6"
        }
    },
    "deployment": {
        "kinsta_site_id": "kinsta_abc123",
        "kinsta_environment": "live",
        "git_repository": "janedoe2026/website",
        "git_branch": "main",
        "deploy_timestamp": "2026-01-20T15:30:45Z",
        "deploy_user": "campaign_admin"
    },
    "plugins": {
        "required": [
            "forminator",
            "wordfence",
            "siteorigin-panels"
        ],
        "recommended": [
            "yoast-seo",
            "wp-super-cache"
        ]
    },
    "security": {
        "geo_blocking": {
            "enabled": true,
            "allowed_countries": ["US", "CA"],
            "mode": "whitelist"
        },
        "login_protection": {
            "two_factor": true,
            "captcha": true,
            "limit_attempts": 5
        }
    },
    "analytics": {
        "google_analytics_id": "G-XXXXXXXXXX",
        "google_tag_manager_id": "GTM-XXXXXX",
        "facebook_pixel_id": "1234567890"
    }
}</code></pre>
                </section>

                <!-- forms-config.json -->
                <section class="content-section">
                    <h2><i class="fas fa-envelope"></i> forms-config.json - Forminator Forms</h2>
                    <p>Defines all forms (contact, volunteer, donation, etc.) with fields, validation, and notifications.</p>

                    <h3>Schema</h3>
                    <pre><code>{
    "forms": [
        {
            "id": "string",              // Unique form identifier
            "name": "string",            // Display name
            "type": "string",            // "contact", "volunteer", "donation", etc.
            "status": "string",          // "publish" or "draft"
            "fields": [
                {
                    "id": "string",      // Field ID (e.g., "name", "email")
                    "type": "string",    // "text", "email", "textarea", "select", "checkbox"
                    "label": "string",   // Field label shown to users
                    "placeholder": "string",
                    "required": "boolean",
                    "validation": {
                        "type": "string", // "email", "phone", "url", "number"
                        "min": "integer",
                        "max": "integer",
                        "pattern": "string" // Regex pattern
                    },
                    "options": ["array"] // For select/radio/checkbox fields
                }
            ],
            "notifications": [
                {
                    "type": "string",     // "user" or "admin"
                    "to": "string",       // Email address or {field_id}
                    "subject": "string",
                    "message": "string",
                    "from_name": "string",
                    "from_email": "string",
                    "reply_to": "string"
                }
            ],
            "settings": {
                "submit_button_text": "string",
                "success_message": "string",
                "error_message": "string",
                "redirect_url": "string",
                "ajax_submit": "boolean",
                "honeypot": "boolean",
                "captcha": "boolean"
            }
        }
    ]
}</code></pre>

                    <h3>Example</h3>
                    <pre><code>{
    "forms": [
        {
            "id": "contact-form",
            "name": "Contact Form",
            "type": "contact",
            "status": "publish",
            "fields": [
                {
                    "id": "name",
                    "type": "text",
                    "label": "Full Name",
                    "placeholder": "Enter your name",
                    "required": true,
                    "validation": {
                        "type": "text",
                        "min": 2,
                        "max": 100
                    }
                },
                {
                    "id": "email",
                    "type": "email",
                    "label": "Email Address",
                    "placeholder": "you@example.com",
                    "required": true,
                    "validation": {
                        "type": "email"
                    }
                },
                {
                    "id": "message",
                    "type": "textarea",
                    "label": "Your Message",
                    "placeholder": "How can we help?",
                    "required": true,
                    "validation": {
                        "min": 10,
                        "max": 1000
                    }
                }
            ],
            "notifications": [
                {
                    "type": "admin",
                    "to": "admin@janedoe2026.com",
                    "subject": "New Contact Form Submission",
                    "message": "Name: {name}\nEmail: {email}\nMessage: {message}",
                    "from_name": "{name}",
                    "from_email": "{email}",
                    "reply_to": "{email}"
                },
                {
                    "type": "user",
                    "to": "{email}",
                    "subject": "Thank you for contacting us",
                    "message": "Hi {name},\n\nWe received your message and will respond soon.",
                    "from_name": "Jane Doe Campaign",
                    "from_email": "noreply@janedoe2026.com"
                }
            ],
            "settings": {
                "submit_button_text": "Send Message",
                "success_message": "Thank you! We'll be in touch soon.",
                "error_message": "Oops! Something went wrong. Please try again.",
                "redirect_url": "",
                "ajax_submit": true,
                "honeypot": true,
                "captcha": true
            }
        }
    ]
}</code></pre>
                </section>

                <!-- Page Layouts JSON -->
                <section class="content-section">
                    <h2><i class="fas fa-layer-group"></i> Page Layouts - SiteOrigin Format</h2>
                    <p>Page layouts built with SiteOrigin Page Builder are stored as JSON with rows, columns, and widgets.</p>

                    <h3>Schema</h3>
                    <pre><code>{
    "page_title": "string",
    "page_slug": "string",
    "page_template": "string",        // "default", "full-width", "landing", etc.
    "page_status": "string",          // "publish", "draft", "private"
    "panels_data": {
        "widgets": [
            {
                "panels_info": {
                    "class": "string",  // Widget class name
                    "grid": "integer",  // Grid/row index
                    "cell": "integer",  // Cell/column index
                    "id": "integer"     // Widget ID
                },
                // Widget-specific fields vary by widget type
                "title": "string",
                "text": "string",
                "image": "string",
                "button_text": "string",
                "button_url": "string"
            }
        ],
        "grids": [
            {
                "cells": "integer",     // Number of columns
                "style": {
                    "background": "string",
                    "background_image": "string",
                    "padding": "string",
                    "row_stretch": "string" // "full", "full-stretched", etc.
                }
            }
        ]
    }
}</code></pre>

                    <h3>Example - Hero Section</h3>
                    <pre><code>{
    "page_title": "Home",
    "page_slug": "home",
    "page_template": "default",
    "page_status": "publish",
    "panels_data": {
        "widgets": [
            {
                "panels_info": {
                    "class": "SiteOrigin_Widget_Hero_Widget",
                    "grid": 0,
                    "cell": 0,
                    "id": 0
                },
                "title": "Fighting for Working Families",
                "subtitle": "Elect Jane Doe to Congress in 2026",
                "text": "Jane Doe is committed to affordable healthcare, quality education, and economic opportunity for all.",
                "buttons": [
                    {
                        "text": "Join Our Campaign",
                        "url": "/volunteer",
                        "style": "primary"
                    },
                    {
                        "text": "Donate Now",
                        "url": "/donate",
                        "style": "secondary"
                    }
                ],
                "background": {
                    "image": "/wp-content/uploads/2026/01/hero-bg.jpg",
                    "overlay_color": "rgba(0,0,0,0.5)",
                    "overlay_opacity": 0.5
                }
            }
        ],
        "grids": [
            {
                "cells": 1,
                "style": {
                    "background": "#14b8a6",
                    "padding": "80px 0",
                    "row_stretch": "full-stretched"
                }
            }
        ]
    }
}</code></pre>
                </section>

                <!-- CPT JSON -->
                <section class="content-section">
                    <h2><i class="fas fa-newspaper"></i> Custom Post Types - Content Structure</h2>
                    <p>News, testimonials, issues, and endorsements follow this standard CPT format.</p>

                    <h3>Schema</h3>
                    <pre><code>{
    "posts": [
        {
            "title": "string",
            "slug": "string",
            "content": "string",          // HTML content
            "excerpt": "string",
            "status": "string",           // "publish", "draft", "future"
            "date": "string",             // ISO 8601 format
            "author": "string",
            "featured_image": "string",   // URL or file path
            "categories": ["array"],
            "tags": ["array"],
            "meta": {
                // Custom fields specific to post type
                "subtitle": "string",
                "testimonial_author": "string",
                "testimonial_location": "string",
                "issue_priority": "integer",
                "endorsement_organization": "string",
                "endorsement_logo": "string"
            }
        }
    ]
}</code></pre>

                    <h3>Example - Testimonial</h3>
                    <pre><code>{
    "posts": [
        {
            "title": "Jane Doe Fights for Small Business",
            "slug": "testimonial-small-business-owner",
            "content": "<p>When I needed help navigating COVID relief programs, Jane Doe's office worked tirelessly to ensure my small business got the support we needed. She truly cares about her constituents.</p>",
            "excerpt": "Local business owner shares how Jane Doe helped during the pandemic.",
            "status": "publish",
            "date": "2026-01-15T10:00:00Z",
            "author": "admin",
            "featured_image": "/wp-content/uploads/2026/01/testimonial-photo.jpg",
            "categories": ["Testimonials"],
            "tags": ["small-business", "covid-relief"],
            "meta": {
                "testimonial_author": "Maria Rodriguez",
                "testimonial_location": "Springfield, IL",
                "testimonial_business": "Maria's Bakery"
            }
        }
    ]
}</code></pre>

                    <h3>Example - Issue</h3>
                    <pre><code>{
    "posts": [
        {
            "title": "Affordable Healthcare for All",
            "slug": "issue-healthcare",
            "content": "<h2>Our Healthcare Plan</h2><p>Every American deserves access to quality, affordable healthcare...</p>",
            "excerpt": "Jane's comprehensive plan to lower healthcare costs and expand coverage.",
            "status": "publish",
            "date": "2026-01-10T12:00:00Z",
            "author": "admin",
            "featured_image": "/wp-content/uploads/2026/01/healthcare-issue.jpg",
            "categories": ["Issues"],
            "tags": ["healthcare", "policy"],
            "meta": {
                "issue_priority": 1,
                "issue_icon": "fa-heartbeat",
                "issue_color": "#ef4444"
            }
        }
    ]
}</code></pre>
                </section>

                <!-- Slider JSON -->
                <section class="content-section">
                    <h2><i class="fas fa-images"></i> Slider Content - Carousel Configuration</h2>
                    <p>Homepage sliders and image carousels use this structure.</p>

                    <h3>Schema</h3>
                    <pre><code>{
    "slider_id": "string",
    "slider_name": "string",
    "slides": [
        {
            "id": "integer",
            "title": "string",
            "subtitle": "string",
            "description": "string",
            "image": "string",            // Background image URL
            "link": "string",             // Click destination URL
            "link_text": "string",        // Button text
            "alignment": "string",        // "left", "center", "right"
            "text_color": "string",       // Hex color
            "overlay_opacity": "float",   // 0.0 to 1.0
            "order": "integer"            // Display order
        }
    ],
    "settings": {
        "autoplay": "boolean",
        "autoplay_speed": "integer",      // Milliseconds
        "transition": "string",           // "fade", "slide", "zoom"
        "transition_speed": "integer",
        "navigation": "boolean",          // Show arrows
        "pagination": "boolean",          // Show dots
        "loop": "boolean"
    }
}</code></pre>

                    <h3>Example</h3>
                    <pre><code>{
    "slider_id": "homepage-slider",
    "slider_name": "Homepage Hero Slider",
    "slides": [
        {
            "id": 1,
            "title": "Fighting for Working Families",
            "subtitle": "Elect Jane Doe to Congress 2026",
            "description": "A proven leader committed to economic opportunity for all.",
            "image": "/wp-content/uploads/2026/01/slide-1.jpg",
            "link": "/about",
            "link_text": "Learn More",
            "alignment": "center",
            "text_color": "#ffffff",
            "overlay_opacity": 0.5,
            "order": 1
        },
        {
            "id": 2,
            "title": "Join Our Campaign",
            "subtitle": "Volunteer Today",
            "description": "Help us reach voters in every corner of the district.",
            "image": "/wp-content/uploads/2026/01/slide-2.jpg",
            "link": "/volunteer",
            "link_text": "Sign Up Now",
            "alignment": "left",
            "text_color": "#ffffff",
            "overlay_opacity": 0.6,
            "order": 2
        }
    ],
    "settings": {
        "autoplay": true,
        "autoplay_speed": 5000,
        "transition": "fade",
        "transition_speed": 800,
        "navigation": true,
        "pagination": true,
        "loop": true
    }
}</code></pre>
                </section>

                <!-- Validation & Best Practices -->
                <section class="content-section">
                    <h2><i class="fas fa-check-circle"></i> Validation & Best Practices</h2>

                    <h3>JSON Validation</h3>
                    <p>Always validate JSON syntax before deployment:</p>
                    <pre><code># Command line validation
jq empty config.json && echo "Valid JSON" || echo "Invalid JSON"

# PHP validation
$json = file_get_contents('config.json');
$data = json_decode($json, true);
if (json_last_error() !== JSON_ERROR_NONE) {
    echo "Error: " . json_last_error_msg();
}</code></pre>

                    <h3>Best Practices</h3>
                    <ul>
                        <li><strong>Use consistent naming:</strong> snake_case for keys (e.g., <code>site_name</code>)</li>
                        <li><strong>Quote strings:</strong> All string values must be in double quotes</li>
                        <li><strong>No trailing commas:</strong> Last item in arrays/objects should not have a comma</li>
                        <li><strong>Escape special characters:</strong> Use <code>\"</code> for quotes inside strings</li>
                        <li><strong>Date format:</strong> Always use ISO 8601 format (YYYY-MM-DDTHH:MM:SSZ)</li>
                        <li><strong>URLs:</strong> Include full URLs with protocol (https://)</li>
                        <li><strong>Colors:</strong> Use hex format (#rrggbb) or rgba(r,g,b,a)</li>
                        <li><strong>Comments:</strong> JSON doesn't support comments - use separate docs</li>
                    </ul>

                    <div class="alert alert-warning">
                        <div class="alert-title">
                            <i class="fas fa-exclamation-triangle"></i>
                            Common Mistakes
                        </div>
                        <ul>
                            <li>Single quotes instead of double quotes: <code>'text'</code> ❌ → <code>"text"</code> ✅</li>
                            <li>Trailing commas: <code>{"a": 1,}</code> ❌ → <code>{"a": 1}</code> ✅</li>
                            <li>Unescaped quotes: <code>"He said "hi""</code> ❌ → <code>"He said \"hi\""</code> ✅</li>
                            <li>Missing quotes on keys: <code>{name: "John"}</code> ❌ → <code>{"name": "John"}</code> ✅</li>
                        </ul>
                    </div>
                </section>

                <!-- Related Resources -->
                <section class="content-section">
                    <h2><i class="fas fa-link"></i> Related Resources</h2>
                    <ul>
                        <li><a href="glossary.php">Glossary - JSON Definition</a></li>
                        <li><a href="scripts-reference.php">Bash Scripts Reference</a></li>
                        <li><a href="deployment-flow.php">Technical Deployment Workflow</a></li>
                        <li><a href="config-site.php">Site Configuration Guide</a></li>
                        <li><a href="config-theme.php">Theme Configuration Guide</a></li>
                    </ul>
                </section>

                <!-- Navigation -->
                <nav class="doc-nav">
                    <a href="glossary.php" class="nav-prev">
                        <i class="fas fa-arrow-left"></i>
                        <div>
                            <span>Previous</span>
                            <strong>Glossary</strong>
                        </div>
                    </a>
                    <a href="scripts-reference.php" class="nav-next">
                        <div>
                            <span>Next</span>
                            <strong>Scripts Reference</strong>
                        </div>
                        <i class="fas fa-arrow-right"></i>
                    </a>
                </nav>
            </div>
        </main>
    </div>
</body>
</html>
